//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IoTFeeder.Common.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IoTFeeder.Common.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept terms &amp; conditions..
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been {0} successfully..
        /// </summary>
        public static string ActionStatus {
            get {
                return ResourceManager.GetString("ActionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been activated successfully..
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully..
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already completed..
        /// </summary>
        public static string AlreadyCompleted {
            get {
                return ResourceManager.GetString("AlreadyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Enter/Select different value..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists in your favourite list..
        /// </summary>
        public static string AlreadyFavourite {
            get {
                return ResourceManager.GetString("AlreadyFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} approved successfully..
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been archived successfully..
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As there are active booking for this tutor, its availability cannot be deleted..
        /// </summary>
        public static string AvailabilityInUse {
            get {
                return ResourceManager.GetString("AvailabilityInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is available..
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Parent/Student Confirmation.
        /// </summary>
        public static string AwaitingParent_StudentConfirmation {
            get {
                return ResourceManager.GetString("AwaitingParent_StudentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting Tutor&apos;s Confirmation.
        /// </summary>
        public static string AwaitingTutorConfirmation {
            get {
                return ResourceManager.GetString("AwaitingTutorConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting your confirmation.
        /// </summary>
        public static string AwaitingYourConfirmation {
            get {
                return ResourceManager.GetString("AwaitingYourConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking completed successfully..
        /// </summary>
        public static string BookingCompleted {
            get {
                return ResourceManager.GetString("BookingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cancelled successfully..
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled by Tutor.
        /// </summary>
        public static string CancelledByTutor {
            get {
                return ResourceManager.GetString("CancelledByTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled: Parent/Student lesson request timed out.
        /// </summary>
        public static string CancelledParent_StudentLessonRequestTimedOut {
            get {
                return ResourceManager.GetString("CancelledParent_StudentLessonRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled - Pending Follow-up.
        /// </summary>
        public static string CancelledPendingFollowUp {
            get {
                return ResourceManager.GetString("CancelledPendingFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled: Tutor&apos;s lesson request timed out.
        /// </summary>
        public static string CancelledTutorLessonRequestTimedOut {
            get {
                return ResourceManager.GetString("CancelledTutorLessonRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled with notice.
        /// </summary>
        public static string CancelledWithNotice {
            get {
                return ResourceManager.GetString("CancelledWithNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled: Your lesson request timed out.
        /// </summary>
        public static string CancelledYourLessonRequestTimedOut {
            get {
                return ResourceManager.GetString("CancelledYourLessonRequestTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be added..
        /// </summary>
        public static string CannotBeAdded {
            get {
                return ResourceManager.GetString("CannotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit this order..
        /// </summary>
        public static string CantEditOrder {
            get {
                return ResourceManager.GetString("CantEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child is already associated with another parent..
        /// </summary>
        public static string ChildAlreadyAssociated {
            get {
                return ResourceManager.GetString("ChildAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With this email this codriver is already added by you..
        /// </summary>
        public static string CodriverExistWithCurrentUser {
            get {
                return ResourceManager.GetString("CodriverExistWithCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} combination with this {1} already exists. Try to choose different value..
        /// </summary>
        public static string CombinationExists {
            get {
                return ResourceManager.GetString("CombinationExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon is not attached with this car.Kindly enter only those coupon which are attached with this car..
        /// </summary>
        public static string CouponNotAttached {
            get {
                return ResourceManager.GetString("CouponNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This coupon is reached its maximum using capacity. Please select/enter different value..
        /// </summary>
        public static string CouponNotAvailable {
            get {
                return ResourceManager.GetString("CouponNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had been successfully updated, changes will be in effect on your next login..
        /// </summary>
        public static string CurrentRoleUpdated {
            get {
                return ResourceManager.GetString("CurrentRoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} declined successfully..
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not uploaded..
        /// </summary>
        public static string DocumentNotUpload {
            get {
                return ResourceManager.GetString("DocumentNotUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document uploaded successfully..
        /// </summary>
        public static string DocumentUploaded {
            get {
                return ResourceManager.GetString("DocumentUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record has been deleted from the system..
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is duplicate..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is verified!.
        /// </summary>
        public static string EamilVerificationSuccess {
            get {
                return ResourceManager.GetString("EamilVerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already registered as a child..
        /// </summary>
        public static string EmailAlreadyRegisteredAsChild {
            get {
                return ResourceManager.GetString("EmailAlreadyRegisteredAsChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already registered as a parent..
        /// </summary>
        public static string EmailAlreadyRegisteredAsParent {
            get {
                return ResourceManager.GetString("EmailAlreadyRegisteredAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is already verified..
        /// </summary>
        public static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was not sent..
        /// </summary>
        public static string EmailNotSuccess {
            get {
                return ResourceManager.GetString("EmailNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found your email is pending for verification. Request you to verify your email to get started..
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has been sent successfully..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification failed..
        /// </summary>
        public static string EmailVerificationFailed {
            get {
                return ResourceManager.GetString("EmailVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some error occured, Please try again..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is expired..
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully signed up with Reconxn..
        /// </summary>
        public static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please filled all the required fileds..
        /// </summary>
        public static string FillUpAllFields {
            get {
                return ResourceManager.GetString("FillUpAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data imported successfullly..
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been inactivated successfully..
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have sufficient balance for weekly recurring booking..
        /// </summary>
        public static string InsufficientBalance {
            get {
                return ResourceManager.GetString("InsufficientBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}..
        /// </summary>
        public static string InValid {
            get {
                return ResourceManager.GetString("InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid first name..
        /// </summary>
        public static string InvalidFirstName {
            get {
                return ResourceManager.GetString("InvalidFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro video link is invalid..
        /// </summary>
        public static string InvalidIntroVideolink {
            get {
                return ResourceManager.GetString("InvalidIntroVideolink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} link is invalid..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string Invalidlogin {
            get {
                return ResourceManager.GetString("Invalidlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain one capital letter, one small letter, one special character and atleast one numeric value and minimum 6 characters allowed..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid phone number..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string Invalidrequest {
            get {
                return ResourceManager.GetString("Invalidrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category/SubCategory is invalid. Enter/Select different value..
        /// </summary>
        public static string InValidSubCategory {
            get {
                return ResourceManager.GetString("InValidSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0} are in use..
        /// </summary>
        public static string IsInUse {
            get {
                return ResourceManager.GetString("IsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail successfully send to {0}..
        /// </summary>
        public static string MailSend {
            get {
                return ResourceManager.GetString("MailSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} marked successfully..
        /// </summary>
        public static string Marked {
            get {
                return ResourceManager.GetString("Marked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {1} characters allowed for {0}..
        /// </summary>
        public static string MaxAllowedLength {
            get {
                return ResourceManager.GetString("MaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The File must be under 250 mb..
        /// </summary>
        public static string MaxFileLength {
            get {
                return ResourceManager.GetString("MaxFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {2} to {1} characters long..
        /// </summary>
        public static string MinMaxAllowedLength {
            get {
                return ResourceManager.GetString("MinMaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one {0}..
        /// </summary>
        public static string MinOneEnter {
            get {
                return ResourceManager.GetString("MinOneEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one {0} for each {1}..
        /// </summary>
        public static string MinOneEnterForEach {
            get {
                return ResourceManager.GetString("MinOneEnterForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found your mobile number is pending for verification. Request you to verify your mobile number to get started..
        /// </summary>
        public static string MobileNumberNotVerified {
            get {
                return ResourceManager.GetString("MobileNumberNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can not be same as old password..
        /// </summary>
        public static string NewPasswordCanNotBeSame {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New wallet pin can not be same as old wallet pin..
        /// </summary>
        public static string NewWalletPinCanNotBeSame {
            get {
                return ResourceManager.GetString("NewWalletPinCanNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a member of JTC Education. Please try with another email..
        /// </summary>
        public static string NoEmailFound {
            get {
                return ResourceManager.GetString("NoEmailFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully. Email was not sent successfully..
        /// </summary>
        public static string NoEmailSent {
            get {
                return ResourceManager.GetString("NoEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are required..
        /// </summary>
        public static string NoOfDays {
            get {
                return ResourceManager.GetString("NoOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one checkbox to delete..
        /// </summary>
        public static string NoSelect {
            get {
                return ResourceManager.GetString("NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not added successfully..
        /// </summary>
        public static string NotAdded {
            get {
                return ResourceManager.GetString("NotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not approved by admin..
        /// </summary>
        public static string NotApproveByAdmin {
            get {
                return ResourceManager.GetString("NotApproveByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not associated..
        /// </summary>
        public static string NotAssociated {
            get {
                return ResourceManager.GetString("NotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view requested page..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available from {1} to {2}. Please select new date..
        /// </summary>
        public static string NotAvailable {
            get {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not changed..
        /// </summary>
        public static string NotChanged {
            get {
                return ResourceManager.GetString("NotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record was not delectable..
        /// </summary>
        public static string NotDelectable {
            get {
                return ResourceManager.GetString("NotDelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This codriver is not delete because it is use in booking..
        /// </summary>
        public static string NotDeleteCoDriverUsedInBooking {
            get {
                return ResourceManager.GetString("NotDeleteCoDriverUsedInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not deleted successfully..
        /// </summary>
        public static string NotDeleted {
            get {
                return ResourceManager.GetString("NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record was not editable..
        /// </summary>
        public static string NotEditable {
            get {
                return ResourceManager.GetString("NotEditable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t edit admin record..
        /// </summary>
        public static string NotEditAdmin {
            get {
                return ResourceManager.GetString("NotEditAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough balance..
        /// </summary>
        public static string NotEnoughBalance {
            get {
                return ResourceManager.GetString("NotEnoughBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not entered/selected any of required field(s)..
        /// </summary>
        public static string NotEnteredRequiredField {
            get {
                return ResourceManager.GetString("NotEnteredRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exists..
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists..
        /// </summary>
        public static string NotExistsUser {
            get {
                return ResourceManager.GetString("NotExistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} found..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has been sent successfully..
        /// </summary>
        public static string NotificationSent {
            get {
                return ResourceManager.GetString("NotificationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Time Slots Available.
        /// </summary>
        public static string NoTimeSlots {
            get {
                return ResourceManager.GetString("NoTimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been not rescheduled..
        /// </summary>
        public static string NotRescheduled {
            get {
                return ResourceManager.GetString("NotRescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1} are must not be same for booking..
        /// </summary>
        public static string NotSame {
            get {
                return ResourceManager.GetString("NotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not {1} successfully..
        /// </summary>
        public static string NotSuccessful {
            get {
                return ResourceManager.GetString("NotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not sufficient wallet balance to withdrawn..
        /// </summary>
        public static string NotSufficientWalletBalance {
            get {
                return ResourceManager.GetString("NotSufficientWalletBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not updated successfully..
        /// </summary>
        public static string NotUpdated {
            get {
                return ResourceManager.GetString("NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload at least one file..
        /// </summary>
        public static string NotUploaded {
            get {
                return ResourceManager.GetString("NotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not verified..
        /// </summary>
        public static string NotVerified {
            get {
                return ResourceManager.GetString("NotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been not added in wish list successfully..
        /// </summary>
        public static string NotWishListAdded {
            get {
                return ResourceManager.GetString("NotWishListAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password do not match with our data, enter proper value..
        /// </summary>
        public static string OldPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("OldPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old wallet pin do not match with our data, enter proper value..
        /// </summary>
        public static string OldWalletPinDoNotMatch {
            get {
                return ResourceManager.GetString("OldWalletPinDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp is not send..
        /// </summary>
        public static string OTPNotSent {
            get {
                return ResourceManager.GetString("OTPNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp has been sent successfully..
        /// </summary>
        public static string OtpSent {
            get {
                return ResourceManager.GetString("OtpSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor Package has been added successfully..
        /// </summary>
        public static string PackageCreated {
            get {
                return ResourceManager.GetString("PackageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutor Package has been updated successfully..
        /// </summary>
        public static string PackageUpdated {
            get {
                return ResourceManager.GetString("PackageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password&apos; and &apos;Password&apos; do not match..
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not changed..
        /// </summary>
        public static string PasswordNotChange {
            get {
                return ResourceManager.GetString("PasswordNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match with our data, enter proper value..
        /// </summary>
        public static string PasswordNotMatched {
            get {
                return ResourceManager.GetString("PasswordNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was not {0} successfully. Any amount if deducted from account will get refunded within 4-5 days..
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have appropriate permision to perform this action..
        /// </summary>
        public static string Permision {
            get {
                return ResourceManager.GetString("Permision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like you neither enter price per hour nor price per day. So you enter must one value..
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile image updated successfully..
        /// </summary>
        public static string ProfileImageUpdated {
            get {
                return ResourceManager.GetString("ProfileImageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been not updated..
        /// </summary>
        public static string ProfileNotUpdated {
            get {
                return ResourceManager.GetString("ProfileNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been updated successfully..
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} purchased successfully..
        /// </summary>
        public static string Purchased {
            get {
                return ResourceManager.GetString("Purchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available quantity and entered quantity do not match..
        /// </summary>
        public static string QuantityMissmatch {
            get {
                return ResourceManager.GetString("QuantityMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral code not matched..
        /// </summary>
        public static string ReferralCodeNotMatched {
            get {
                return ResourceManager.GetString("ReferralCodeNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed, Please try again..
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} rejected successfully..
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been removed from wish list successfully..
        /// </summary>
        public static string RemoveFromWishList {
            get {
                return ResourceManager.GetString("RemoveFromWishList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled by Parent/Student.
        /// </summary>
        public static string RequestCancelledByParent_Student {
            get {
                return ResourceManager.GetString("RequestCancelledByParent_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled by Tutor.
        /// </summary>
        public static string RequestCancelledByTutor {
            get {
                return ResourceManager.GetString("RequestCancelledByTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request cancelled by you.
        /// </summary>
        public static string RequestCancelledByYou {
            get {
                return ResourceManager.GetString("RequestCancelledByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request declined by Parent/Student.
        /// </summary>
        public static string RequestDeclinedByParent_Student {
            get {
                return ResourceManager.GetString("RequestDeclinedByParent_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request declined by Tutor.
        /// </summary>
        public static string RequestDeclinedByTutor {
            get {
                return ResourceManager.GetString("RequestDeclinedByTutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request declined by you.
        /// </summary>
        public static string RequestDeclinedByYou {
            get {
                return ResourceManager.GetString("RequestDeclinedByYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request from Parent/Student timed out.
        /// </summary>
        public static string RequestFromParent_StudentTimedOut {
            get {
                return ResourceManager.GetString("RequestFromParent_StudentTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been rescheduled successfully..
        /// </summary>
        public static string Rescheduled {
            get {
                return ResourceManager.GetString("Rescheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email has been sent to your registered email address..
        /// </summary>
        public static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resolved successfully..
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been sent successfully..
        /// </summary>
        public static string SendSuccess {
            get {
                return ResourceManager.GetString("SendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session was expired, Please make entries again and save the record..
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged into Reconxn..
        /// </summary>
        public static string SignInSuccess {
            get {
                return ResourceManager.GetString("SignInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully register with JTC..
        /// </summary>
        public static string SignupSuccess {
            get {
                return ResourceManager.GetString("SignupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully register with JTC. Verify email was not sent successfully..
        /// </summary>
        public static string SignupSuccessEmailNotSent {
            get {
                return ResourceManager.GetString("SignupSuccessEmailNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} status has been changed successfully..
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deactivate successfully..
        /// </summary>
        public static string StatusChange {
            get {
                return ResourceManager.GetString("StatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been changed successfully..
        /// </summary>
        public static string SuccessChanged {
            get {
                return ResourceManager.GetString("SuccessChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully..
        /// </summary>
        public static string SuccessChangePassword {
            get {
                return ResourceManager.GetString("SuccessChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been {1} successfully..
        /// </summary>
        public static string Successfully {
            get {
                return ResourceManager.GetString("Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful..
        /// </summary>
        public static string SuccessLogin {
            get {
                return ResourceManager.GetString("SuccessLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out from the system..
        /// </summary>
        public static string SuccessLogOut {
            get {
                return ResourceManager.GetString("SuccessLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string SuccessResetPassword {
            get {
                return ResourceManager.GetString("SuccessResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tickets completed successfully..
        /// </summary>
        public static string TicketCompletedSuccess {
            get {
                return ResourceManager.GetString("TicketCompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with your Apple account.
        /// </summary>
        public static string TryWithApple {
            get {
                return ResourceManager.GetString("TryWithApple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with your Facebook account.
        /// </summary>
        public static string TryWithFacebook {
            get {
                return ResourceManager.GetString("TryWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with your Google account.
        /// </summary>
        public static string TryWithGoogle {
            get {
                return ResourceManager.GetString("TryWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try with normal login.
        /// </summary>
        public static string TryWithNormal {
            get {
                return ResourceManager.GetString("TryWithNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been unarchived successfully..
        /// </summary>
        public static string Unarchived {
            get {
                return ResourceManager.GetString("Unarchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unmarked successfully..
        /// </summary>
        public static string Unmarked {
            get {
                return ResourceManager.GetString("Unmarked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated in {1} successfully..
        /// </summary>
        public static string UpdatedInMaintenance {
            get {
                return ResourceManager.GetString("UpdatedInMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload at least one photo..
        /// </summary>
        public static string UploadAtleastOnePhoto {
            get {
                return ResourceManager.GetString("UploadAtleastOnePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size should not be more than {0} MB..
        /// </summary>
        public static string UploadMaxFileSize {
            get {
                return ResourceManager.GetString("UploadMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload files with {0} extensions only..
        /// </summary>
        public static string UploadOnlyValidFile {
            get {
                return ResourceManager.GetString("UploadOnlyValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url is not valid..
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile has been updated successfully..
        /// </summary>
        public static string UserProfileUpdated {
            get {
                return ResourceManager.GetString("UserProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Enter/Select different value..
        /// </summary>
        public static string ValueNotAvailable {
            get {
                return ResourceManager.GetString("ValueNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} verified successfully..
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet pin not changed..
        /// </summary>
        public static string WalletPinNotChange {
            get {
                return ResourceManager.GetString("WalletPinNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added in wish list successfully..
        /// </summary>
        public static string WishListAdded {
            get {
                return ResourceManager.GetString("WishListAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is wrong..
        /// </summary>
        public static string WrongUsername {
            get {
                return ResourceManager.GetString("WrongUsername", resourceCulture);
            }
        }
    }
}
